name: training_clean_architecture
description: Flutter project for raising skill in clean architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  http: ^0.13.4
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  dartz: ^0.10.1
  connectivity: ^3.0.6
  connectivity_plus: ^2.3.4
  internet_connection_checker: ^0.0.1+4
  json_serializable: ^6.2.0
  chopper: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.2.0
  build_runner: ^2.1.1
  chopper_generator: ^4.0.6

flutter:
  uses-material-design: true
